env:
  browser: true
  es6: true
  node: true
parserOptions:
  ecmaVersion: 6
  sourceType: 'script'
extends: 'eslint:recommended'
rules:
  indent:
    - error
    - tab
  linebreak-style:
    - warn
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  no-unused-vars:
    - warn
  no-console: off
# globals:
#   Promise: on
#   jQuery:
#   $:
#   _:
#   moment:
#   terr:
#   bootbox:
#   Cases: