# -*- coding: utf-8 -*-
"""madlad.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CNfGaWzCA4s1fiAy_BMpgXYB397j3G5_
"""

# !pip uninstall -y transformers
!pip install transformers accelerate sentencepiece langdetect

# import transformers
# print(transformers.__version__)
from transformers import T5ForConditionalGeneration, T5Tokenizer
import torch
from langdetect import detect

model_name = 'google/madlad400-3b-mt'
model = T5ForConditionalGeneration.from_pretrained(model_name, device_map="auto")
tokenizer = T5Tokenizer.from_pretrained(model_name)

def detect_language(text):
    """
    Автоматичне визначення мови тексту
    """
    try:
        detected_lang = detect(text)
        print(f"🔍 Визначена мова: {detected_lang}")
        return detected_lang
    except e:
        print("⚠️ Не вдалося визначити мову, використовую англійську за замовчуванням")
        return "en"

def translate_text(text, target_lang="uk", max_length=512, source_lang=None):
    """
    Переклад тексту з автоматичним визначенням мови та налаштуваннями для кращої якості
    """
    # Автоматично визначаємо мову, якщо не вказана
    if source_lang is None:
        source_lang = detect_language(text)

    # Додаємо спеціальний токен для перекладу
    formatted_text = f"<2{target_lang}> {text}"

    # Токенізуємо текст
    input_ids = tokenizer(
        formatted_text,
        return_tensors="pt",
        max_length=max_length,
        truncation=True,
        padding=True
    ).input_ids.to(model.device)

    print(f"📝 Довжина вхідних токенів: {input_ids.shape[1]}")

    # Генеруємо переклад з покращеними параметрами
    with torch.no_grad():
        outputs = model.generate(
            input_ids=input_ids,
            max_length=max_length,  # Максимальна довжина виходу
            min_length=10,  # Мінімальна довжина
            num_beams=4,    # Використання beam search для кращої якості
            early_stopping=True,
            do_sample=False,  # Детермінований вивід
            temperature=1.0,
            pad_token_id=tokenizer.pad_token_id,
            eos_token_id=tokenizer.eos_token_id,
        )

    # Декодуємо результат
    result = tokenizer.decode(outputs[0], skip_special_tokens=True)
    return result

def translate_long_text(text, target_lang="uk", chunk_size=400, source_lang=None):
    """
    Переклад довгого тексту по частинах з автоматичним визначенням мови
    """
    # Визначаємо мову один раз для всього тексту
    if source_lang is None:
        source_lang = detect_language(text)

    # Розбиваємо текст на речення
    sentences = text.split('. ')

    translated_parts = []
    current_chunk = ""

    for sentence in sentences:
        # Перевіряємо, чи не перевищить наступна частина ліміт
        test_chunk = current_chunk + sentence + ". "

        if len(tokenizer.encode(test_chunk)) < chunk_size:
            current_chunk = test_chunk
        else:
            # Перекладаємо поточну частину
            if current_chunk.strip():
                print(f"🔄 Перекладаю частину: {current_chunk[:50]}...")
                translated = translate_text(current_chunk.strip(), target_lang, max_length=1024, source_lang=source_lang)
                translated_parts.append(translated)

            # Починаємо нову частину
            current_chunk = sentence + ". "

    # Перекладаємо останню частину
    if current_chunk.strip():
        print(f"🔄 Перекладаю останню частину: {current_chunk[:50]}...")
        translated = translate_text(current_chunk.strip(), target_lang, max_length=1024, source_lang=source_lang)
        translated_parts.append(translated)

    return " ".join(translated_parts)

text = """<2uk> In seinem Post warf Trump Monaco vor, korrupt zu sein, ohne dies weiter zu begründen. Wegen ihrer angeblichen Verfehlungen habe die US-Regierung ihr zuletzt alle Sicherheitsfreigaben entzogen, ihr jeglichen Zugang zu nationalen Sicherheitsinformationen untersagt und ihr den Zutritt zu sämtlichen Bundesgebäuden verboten. Was genau sie falsch gemacht haben soll, sagte Trump nicht und lieferte auch keinerlei Hinweise.
Monaco war Sicherheitsberaterin in der Regierung des früheren demokratischen Präsidenten Barack Obama und stellvertretende Justizministerin unter dem ehemaligen demokratischen Präsidenten Joe Biden. Sie arbeitet seit Juli für Microsoft.
Trump setzt damit seine Vergeltungskampagne gegen seine politischen Gegner fort. Das US-Justizministerium hatte am Donnerstag Anklage gegen den früheren FBI-Direktor James Comey erhoben (mehr dazu lesen Sie hier ). Er hatte die Bundespolizei FBI geleitet, als diese eine Untersuchung der Verbindungen zwischen Trumps Wahlkampfteam 2016 und der russischen Regierung einleitete.
Comey werden Falschaussage und die Behinderung einer Untersuchung des Kongresses vorgeworfen. Bei einer Verurteilung drohen Comey bis zu fünf Jahre Haft. Trump sagte am Freitag, er erwarte weitere Anklagen gegen von ihm als Feinde wahrgenommene Personen. »Ich denke, es wird andere geben«, sagte er vor Reportern, fügte jedoch hinzu, er habe keine Liste.
"""
# input_ids = tokenizer(text, return_tensors="pt").input_ids.to(model.device)
# outputs = model.generate(input_ids=input_ids)

# result = tokenizer.decode(outputs[0], skip_special_tokens=True)
# print(result)

print("🚀 Початок перекладу...")
print("📜 Оригінальний текст:")
print(text)
print("\n" + "="*50 + "\n")

# Спробуємо спочатку простий переклад
print("🎯 Простий переклад:")
simple_result = translate_text(text, max_length=1024)
print(f"✅ Результат: {simple_result}")

print("\n" + "="*50 + "\n")

# Якщо простий переклад неповний, використовуємо переклад по частинах
# print("🔧 Переклад по частинах:")
# chunked_result = translate_long_text(text)
# print(f"✅ Результат: {chunked_result}")