env:
  es6: true
  node: true
extends: 'eslint:recommended'
parserOptions:
  sourceType: module
rules:
  indent:
    - warn
    - tab
  linebreak-style:
    - ignore
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  no-console: off
