#!/usr/bin/env python

# -*- coding: utf-8 -*-
"""gemma3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n-_NIuQImzJJJKP6VtGYaUGJ_5LLcYVN
"""

# !pip install transformers accelerate

from transformers import AutoTokenizer, AutoModelForCausalLM
import torch

tokenizer = AutoTokenizer.from_pretrained("google/gemma-3-4b-it")
model = AutoModelForCausalLM.from_pretrained(
    "google/gemma-3-4b-it",
    device_map="auto",
    torch_dtype=torch.bfloat16,
)

input_text = """Переклади текст нижче українською мовою. виведи лише переклад. Ось текст:
Ein Regionaljet mit 53 Passagieren und Crewmitgliedern schoss auf dem Roanoke-Blacksburg Regional Airport im amerikanischen Bundesstaat Virginia über die Landebahn hinaus und kam nicht rechtzeitig zum Stehen. Zement-Zone stoppt Flieger
Das Flugzeug wurde jedoch erfolgreich durch ein spezielles Sicherheitssystem gestoppt: eine mit Zementblöcken ausgelegte Sicherheitszone. Dadurch wurde ein Unfall verhindert, und es gab keine Verletzten unter den Insassen, berichtet das „Wall Street Journal“."""
input_ids = tokenizer(input_text, return_tensors="pt").to("cuda")

# outputs = model.generate(**input_ids, max_new_tokens=32)
outputs = model.generate(**input_ids)
print(tokenizer.decode(outputs[0]))
