[project]
name = "vllm-text"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "openai>=2.2.0",
    "ruff>=0.13.3",
    "vllm>=0.11.0",
]
