[project]
name = "vllm-text"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.118.0",
    "openai>=2.2.0",
    "pydantic>=2.11.10",
    "ruff>=0.13.3",
    "uvicorn[standard]>=0.37.0",
    "vllm>=0.11.0",
]
